// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['internal']['App']['CloseWindow']();
}

export function Minimize() {
  return window['go']['internal']['App']['Minimize']();
}

export function Notify(arg1) {
  return window['go']['internal']['App']['Notify'](arg1);
}

export function ToggleMaximize() {
  return window['go']['internal']['App']['ToggleMaximize']();
}
